//
//  Session+CoreDataClass.swift
//  Rehab Tracker
//
//  Created by Sean Kates on 12/5/16.
//  Copyright © 2017 University of Vermont. All rights reserved.
//

import Foundation
import CoreData

/// Create an entity in core data for every session. This file and the properties file are generated by Xcode.
public class Session: NSManagedObject {

}
