author: Chia-Chun Chao
module: Rehab_Tracker 
min_acl: private 
output: "../Documentation/jazzy" 
source_directory: "../Rehab Tracker/"
readme: "README.md"
exclude: "../Rehab Tracker/Rehab Tracker/StatsViewController.swift"
